CREATE TABLE SCHEDULE
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '일정 식별자',
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    updated_at  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    author_name VARCHAR(100) NOT NULL COMMENT '작성자명',
    password    VARCHAR(100) NOT NULL COMMENT '비밀번호',
    task        VARCHAR(200) NOT NULL COMMENT '할일'
);