CREATE TABLE SCHEDULE
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '일정 식별자',
    title       VARCHAR(100) NOT NULL COMMENT '제목',
    contents    TEXT COMMENT '내용',
    createdAt   DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    updatedAt   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    authorName  VARCHAR(100) NOT NULL COMMENT '작성자명',
    password    VARCHAR(100) NOT NULL COMMENT '비밀번호'
);